Modification to Dockerfile
nearform/bioconductor.org pull request #12
Opened 2023-07-10 11:56 UTC by MariamM110

Before when trying to create a docker image, there would be multiple errors preventing the developer from running the image and accessing the files in localhost.

2023-07-11 08:02 UTC, SociableSteve commented on Dockerfile
> +WORKDIR /tmp/bioconductor.org
We should probably not use `/tmp` as a working directory. `/tmp` is generally reserved for temporary files, and while this may not be an issue it's not best practice. `/opt` is a better option.

2023-07-11 08:03 UTC, SociableSteve commented on Dockerfile
> +RUN echo '#! /bin/bash' > .startup.sh \
Did this need to be split across multiple lines like this? It works, but also is a change that we might not need to make.

2023-07-11 11:15 UTC, Mariam-mohamed110 commented on Dockerfile
> +RUN echo '#! /bin/bash' > .startup.sh \
When trying to write this code without using multiple lines or not specifying after each command to add to the .startup script, the docker image just doesn't seem to run. It may be that I wrote the code wrong but for now this structure was the only way that allowed me to build the image

2023-07-11 21:33 UTC, SociableSteve requested changes
There's a lot of changes in the README which are unrelated to the changes you're actually making. I presume these are from a linter of some kind. It's worth trying to reduce the scope of changes to make it easier to understand what we're doing and why.

2023-07-11 21:33 UTC, SociableSteve commented on README.md
> +        - t is the name of docker image
maybe update this to `<image_name> is the name you want to give to the docker image. This can be whatever you want and will be used later to reference the image.`

2023-07-11 21:33 UTC, SociableSteve commented on README.md
> +        -it will take you straight to the container
is `-it` the default we want, or do we want `-d` to run it in the background?

2023-07-11 21:33 UTC, SociableSteve commented on README.md
> +        docker run -it -p 3000:3000 \
it's probably worth naming the container for easier reference later

2023-07-11 21:33 UTC, SociableSteve commented on README.md
> +        docker kill <CONTAINER ID>
does it need to be `kill` or will `stop` work? people might be put off by the finality of `kill` 😬

2023-07-11 21:33 UTC, SociableSteve commented on README.md
> +7.  Before you run the docker image again with more changes, make sure
you can add things to `.dockerignore` if you think they shouldn't be included in the built image. i feel like it uses `.gitignore` by default if it's available but i might be making that up.

2023-07-12 09:00 UTC, MariamM110 commented on README.md
> +        -it will take you straight to the container
We want -it to be able to get the shell immediately and run the rake and adsf commands. Any other technique doesnt seem to work

2023-07-12 09:02 UTC, Mariam-mohamed110 commented on README.md
> +        docker kill <CONTAINER ID>
Anything after step 5 was mostly the Bioconductors code which i thought to keep the same, but I agree with the `kill` ill change that to `stop`. What if the person wants to remove the container though? Shall I add another step to say if you want to get rid of it?

2023-07-12 10:55 UTC, SociableSteve commented on README.md
> +        docker kill <CONTAINER ID>
You can add something that explains how to remove it when they're done using it, that makes sense. I imagine a number of the people joining the project won't have used Docker in the past.

2023-07-12 16:24 UTC, SociableSteve requested changes

2023-07-12 16:24 UTC, SociableSteve commented on README.md
> +        It can be whatever you want as it will be referenced later
change `it can be whatever you want as it` to `it can be whatever you want. You will need to use it later but is only seen and used by you.`

2023-07-12 16:24 UTC, SociableSteve commented on README.md
> +        -it will take you straight to the container
I thought the startup script runs rake and then adsf. `-d` will still make it run but won't need to do the manual rake.

2023-07-12 16:24 UTC, SociableSteve commented on README.md
> +        docker kill <container_id / container_name>
`kill` doesn't remove a container, it only stops it forcefully. In order to remove it you need to use `docker rm`

2023-07-12 16:51 UTC, Mariam-mohamed110 commented on README.md
> +        docker kill <container_id / container_name>
In that case shall I make a section for: 
- stopping a container forcefully in the event that docker stop doesnt work
- to remove the container completely

2023-07-12 16:53 UTC, SociableSteve commented on README.md
> +        docker kill <container_id / container_name>
I think docker `stop` will fall to `kill` if the container doesn't stop after 10 seconds automatically, so you don't really need to put anything. In terms of how to remove it feel free to add something :)

2023-07-13 09:04 UTC, Mariam-mohamed110 commented on README.md
> +        -it will take you straight to the container
When I add the volume to the command the script doesnt seem to pick up what to do, it gives me multiple errors. It wasnt until i ran this -it command with the bin/bash at the end that it worked? 
If I was just running the docker command without having to mount the volume then docker run <container> would actually just do.

2023-07-13 11:15 UTC, SociableSteve approved these changes

2023-07-13 11:32 UTC, merged