added ability to run only if it is not on draft pr
nearform/bioconductor.org pull request #16
Opened 2023-07-11 13:52 UTC by bp289

Changes made :
- Linter added for stylint.
- Added action for Linters to run on push.
- Action should run as long as it is not a draft pull request.

2023-07-11 21:35 UTC, SociableSteve requested changes

2023-07-11 21:35 UTC, SociableSteve commented on package.json
> +  "description": "[CloudFront](https://aws.amazon.com/cloudfront/) is a content delivery network (CDN). The idea is that if a user in say, Singapore hits our web site, the files she requested will be
Is this description accurate? It seems to be describing CloudFront rather than what this package is for.

2023-07-11 21:35 UTC, SociableSteve commented on .github/workflows/linter.yaml
> +name: Run Linters
I see that you're checking out the code, then running super-linter. At what point are the NPM packages installed?

2023-07-12 09:02 UTC, bp289 commented on .github/workflows/linter.yaml
> +name: Run Linters
For the super linter action, I believe we won't need to install NPM packages because it has its own NPM packages that it needs to install here https://github.com/super-linter/super-linter/blob/main/dependencies/package.json. 
I thought it might be useful to include the package.json here so we could easily install the stylelint on our own machines.

2023-07-12 10:59 UTC, SociableSteve commented on .github/workflows/linter.yaml
> +name: Run Linters
I'd recommend that rather than installing a package.json, find out if running npx as a single command would also do the linting. If it does, then there's no really a need for the package.json at the moment and it's adding complexity which might not be needed. If the npx command can work then add something into the README about doing linting (i.e. run `npx stylelint`)

If the npx command doesn't work as you'd want, then adding the package.json seems fine, just need to make sure we're not adding more at this stage than needed.

2023-07-12 12:54 UTC, bp289 commented on .github/workflows/linter.yaml
> +name: Run Linters
Just updated the readme, yes the npx stylelint would work.

2023-07-12 16:27 UTC, SociableSteve requested changes
A couple of comment. Need to update the README with instructions on how to run the linting locally.

2023-07-12 16:27 UTC, SociableSteve commented on package.json
> +  "dependencies": {
Why are there so many dependencies in here 🙈 How many of these does your script actually depend on?

2023-07-12 16:27 UTC, SociableSteve commented on .github/workflows/linter.yaml
> +name: Run Linters
Makes sense if you're adding more to it.

2023-07-12 16:27 UTC, SociableSteve commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Add a `linting` script to run the linting tools.

2023-07-12 17:13 UTC, bp289 commented on package.json
> +  "dependencies": {
I've removed the entire dependencies section and added just added it to the devDependencies. Sorry, I originally assumed you would need all of them as that's what was generated when running npm init stylelint. Which is what the documentation says. But after some investigation, it turns out we can just run npx stylelint "**/*.css" without it. And eslint works fine too.

2023-07-13 11:18 UTC, SociableSteve requested changes

2023-07-13 11:18 UTC, SociableSteve commented on package.json
> +    "lint-all": " npx stylelint \"**/*.css\"  \n npx eslint assets/js",
Rename `lint-all` to just `lint`. It's a bit more in line with common standards.

2023-07-13 11:18 UTC, SociableSteve commented on README.md
> +### Linters
You'll probably want to add instructions that node and npm are required.

2023-07-15 19:04 UTC, SociableSteve requested changes

2023-07-15 19:04 UTC, SociableSteve commented on README.md
> -        -p is mapping the container's port 3000 to the host machine's port
There's a lot of whitespace surrounding this line. Does this need to change?

2023-07-17 08:46 UTC, bp289 commented on README.md
> -        -p is mapping the container's port 3000 to the host machine's port
does not appear to need it, removed it in the latest push.

2023-07-17 09:54 UTC, SociableSteve requested changes

2023-07-17 09:54 UTC, SociableSteve commented on package.json
> +    "lint": " npx stylelint \"**/*.css\"  \n npx eslint assets/js",
change this to `npm run css-lint && npm run js-lint` so you've got only one place to change if you need to.

2023-07-17 09:57 UTC, SociableSteve commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
can you remove this test line? it's a small thing but we don't have and won't have any tests

2023-07-17 09:59 UTC, SociableSteve submitted a review, later dismissed

2023-07-17 10:25 UTC, SociableSteve approved these changes

2023-07-17 10:27 UTC, merged