Workflows/kpi automation
nearform/bioconductor.org pull request #22
Opened 2023-07-12 14:34 UTC by bp289

Closes #7 
Changes made : 
- Once the staging is deployed, the KPIs will be assessed in Pagespeed and Axe, currently printed out to the console. Decided to do wave evaluation manually every time we deploy to staging. 
- Should get things ready for #21 to be done.

2023-07-13 11:23 UTC, SociableSteve commented on .gitignore
Are these changes meant for this branch?

2023-07-13 11:28 UTC, SociableSteve commented
What happens to the output of the actions?

2023-07-13 12:09 UTC, bp289 commented on .gitignore
Its not a change for this branch, however the gitignore is not already merged into main so I wanted to put it in here incase it does not upload my node modules from my machine, should i just delete the node modules and remove it from the pr ?

2023-07-13 12:13 UTC, bp289 commented
> What happens to the output of the actions?

Currently it is just displaying in the console, I though we were putting it into the spreadsheet manually, where should i pipe the output of the console into a txt file, and into an s3 bucket or something of the sort ?

2023-07-15 19:03 UTC, SociableSteve requested changes

2023-07-15 19:03 UTC, SociableSteve commented on .github/workflows/pr_deploy.yaml
> +          npm install psi
why is `psi` local, but `@axe-core/cli` global?

2023-07-15 19:03 UTC, SociableSteve commented on .github/workflows/pr_deploy.yaml
> +          echo "$(node psi.js ${{env.URL_TO_USE}} desktop 50)" >> $GITHUB_ENV
How can we prepare for multiple URLs here? We will want to run multiple of them at once with a change. Initially this will just be the homepage, but we'll need to have multiple pages eventually.

2023-07-17 08:59 UTC, bp289 commented on .github/workflows/pr_deploy.yaml
> +          npm install psi
Axe instructs to install axe-core/cli globally to be able to use it as a cli tool. But I assume for our use case it should be fine to install locally and change it to `npx axe <URL>` which I've tested on my machine and should work when installed locally.

2023-07-17 09:05 UTC, bp289 commented on .github/workflows/pr_deploy.yaml
> +          echo "$(node psi.js ${{env.URL_TO_USE}} desktop 50)" >> $GITHUB_ENV
With axe we can chain urls onto the command e.g `axe ${url1} ${url2} ${url3}`. For SEO and performance, since we are running our own script to query page speed, we should be able to implement a feature where we can provide an array of URLs that the script loops through, may need an API key for this though.

2023-07-18 09:13 UTC, SociableSteve requested changes

2023-07-18 09:13 UTC, SociableSteve commented on .github/workflows/staging.yaml
> +          echo "DESKTOP_PSI_RESULTS<<EOF" >> $GITHUB_ENV
do these need to be multi-line? do they need to be put into `$GITHUB_ENV`? it looks like you could do this on a single line since there's only a single command on each.

`run: DESKTOP_PSI_RESULTS << $(node psi.js ${{env.URL_TO_USE}} desktop 50)` might do what you need, for example.

This is the same in a few files - might be worth trying and see if you can simplify

2023-07-18 09:13 UTC, SociableSteve commented on psi.js
should probably rename this to something else - psi isn't really descriptive that it's running page speed insights.

2023-07-18 09:13 UTC, SociableSteve commented on psi.js
> +    const threshold = Number(thresholdInput);
What if these parameters are missing? If they're not required then it might be better to be a bit more explicit about that. If they are required, there's no check for them existing.

2023-07-18 09:13 UTC, SociableSteve commented on psi.js
> +    const strategy = strategyInput;
There's no check around this input. Either use directly or, preferably, check that the value make sense based on a list or format of input.

2023-07-18 11:08 UTC, bp289 commented on .github/workflows/staging.yaml
> +          echo "DESKTOP_PSI_RESULTS<<EOF" >> $GITHUB_ENV
Unfortunately, I can't seem to find a way of doing it without the multi-line `EOF`,  whenever I try to set the variable without it, I get an error. 

As for the `$GITHUB_ENV` I've tried using `run: DESKTOP_PSI_RESULTS << $(node psi.js ${{env.URL_TO_USE}} desktop 50)`, however, I get an error saying it's not a valid command.

I have also tried ` DESKTOP_PSI_RESULTS=$(node psi.js https://www.bioconductor.org/ desktop 50)` which seemed to work, but when I try to print the variable using:   
`echo {{env.DESKTOP_PSI_RESULTS}}` Or `echo "$DESKTOP_PSI_RESULTS"`
 but they both print nothing in the console. The only one which seems to retain all the information i need is the  $GITHUB_ENV with the EOF.

2023-07-18 11:38 UTC, bp289 commented
> > What happens to the output of the actions?
> 
> Currently it is just displaying in the console, I though we were putting it into the spreadsheet manually, where should i pipe the output of the console into a txt file, and into an s3 bucket or something of the sort ?

Now slack notifications are sent on staging and on pull requests, there will be comments.

2023-07-18 13:26 UTC, SociableSteve commented on .github/workflows/staging.yaml
> +          echo "DESKTOP_PSI_RESULTS<<EOF" >> $GITHUB_ENV
I suspect the single line command might need quotes or something similar to work. If you can't get it down to a single line that's fine, but it'd make more sense to do that if we can.

2023-07-18 14:10 UTC, bp289 commented on .github/workflows/staging.yaml
> +          echo "DESKTOP_PSI_RESULTS<<EOF" >> $GITHUB_ENV
I've tried a few more things: 

" DESKTOP_PSI_RESULTS=$(echo node psi.js https://www.bioconductor.org/ desktop 50) "
" DESKTOP_PSI_RESULTS=\`node psi.js https://www.bioconductor.org/ desktop 50)\` "
" DESKTOP_PSI_RESULTS=\`echo node psi.js https://www.bioconductor.org/ desktop 50\` "

However on the next step after we run:
` - name: next step
        run: |
          echo $DESKTOP_PSI_RESULTS
`
It just prints out nothing, I dont think the syntax is incorrect because I've checked this against the documentation here: 
https://www.cyberciti.biz/faq/unix-linux-bsd-appleosx-bash-assign-variable-command-output/

I cant find any other way to do it, unfortunately.

2023-07-18 14:26 UTC, SociableSteve commented on .github/workflows/staging.yaml
> +          echo "DESKTOP_PSI_RESULTS<<EOF" >> $GITHUB_ENV
OK, let's go with what's here. I'll do a full review now :D

2023-07-18 14:27 UTC, SociableSteve approved these changes

2023-07-18 14:51 UTC, merged