New project structure #10
nearform/bioconductor.org pull request #23
Opened 2023-07-12 16:55 UTC by Mariam-mohamed110

closes #10 

Initial idea on how to restructure the project. The key idea is to have a section that allows us to recognise which components have been edited and improved.

2023-07-15 19:00 UTC, SociableSteve requested changes

2023-07-15 19:00 UTC, SociableSteve commented on README.md
> +            - Content and the other folders always have two related files:
What are the other folders?

2023-07-15 19:00 UTC, SociableSteve commented on README.md
> +            - The default behavior is that the `index.md` in each folder
I'd keep the previous comment, and maybe add something about `index` being the default file within a folder

2023-07-15 19:00 UTC, SociableSteve commented on README.md
> +            - Files that live directly inside the layout folder are the old
old and new are kinda relative. I know what you're trying to say but perhaps try something about the content blocks living inside `layouts/components` for legacy support, and the page layouts living inside layouts

2023-07-15 19:00 UTC, SociableSteve commented on layouts/components/README.md
> +The purpose of the new components folder is to house the new layouts.
remove the word `new` throughout. also the `components` folder stores stand-alone components to be included in pages, rather than full layouts.

2023-07-17 08:41 UTC, Mariam-mohamed110 commented on README.md
> +            - Content and the other folders always have two related files:
So it would be about, developers, help and news those folders would also have 2 two related files

2023-07-17 09:55 UTC, SociableSteve commented on README.md
> +            - Content and the other folders always have two related files:
You can put `Each page has two related files:` then discuss about the config `.yaml` file and the `.md OR .html` content file

2023-07-17 10:37 UTC, SociableSteve approved these changes

2023-07-17 10:55 UTC, merged