Css font format
nearform/bioconductor.org pull request #35
Opened 2023-07-17 12:28 UTC by Mariam-mohamed110

closes #18 

- A new css file has been created `bioconductor-v2.css` which will eventually be the new main css file
- Added the style font that will be used throughout the site it contains the global styles + colour variables that can be easily reused
- Removed the global styles from the original `bioconductor.css` file
- A font format has been added with a fallback of `Sans-serif`

2023-07-17 14:32 UTC, bp289 commented on assets/style/bioconductor-v2.css
could we split the bioconductor-v2 file into a fonts.css and a colors.css file ?

2023-07-17 16:38 UTC, Mariam-mohamed110 commented on assets/style/bioconductor-v2.css
Thats a good cleaner idea

2023-07-18 11:08 UTC, SociableSteve requested changes

2023-07-18 11:08 UTC, SociableSteve commented on layouts/_sitehead.html
>    <link rel="stylesheet" type="text/css" href="/style/bioconductor-v2.css" media="screen" />
Do the variables need to be defined above the main style? If `bioconductor-v2` uses the variables then load order is important, and it's useful for cognitive understanding as well.

2023-07-18 11:08 UTC, SociableSteve commented on assets/style/colors.css
Do we have any tree-shaking in place (i.e. remove unused things like styling at build time)? It would be good to avoid adding things that we're not using to avoid confusion and to not introduce dead code from the start.

2023-07-18 11:08 UTC, SociableSteve commented on assets/style/fonts.css
> +h1 {
Probably something to discuss with Nick but we should try and do these using `rem` instead for accessibility reasons. Default `rem` is 16, so this would be `2.25rem`. It might mean adjusting some sizes slightly (e.g. 31px because 2rem or 32px) to make it easier to understand.

2023-07-18 11:08 UTC, SociableSteve commented on assets/style/fonts.css
> +  font-family: "Atkinson Hyperlegible", sans-serif;
Is this going to be the default font? If so you can set it on the body, or *

2023-07-18 11:16 UTC, Mariam-mohamed110 commented on layouts/_sitehead.html
>    <link rel="stylesheet" type="text/css" href="/style/bioconductor-v2.css" media="screen" />
So the font and color css should be placed at the top then everything else down below?

2023-07-18 11:33 UTC, MariamM110 commented on assets/style/colors.css
Im not sure if we do have any tree-shaking in place, that would be great to filter out all the unused styling

2023-07-18 13:23 UTC, SociableSteve requested changes

2023-07-18 13:23 UTC, SociableSteve commented on assets/style/bioconductor-v2.css
> +  width: 100rem; /* change the site design width here */
For a fixed-width we probably want to keep it fixed size, so pixels rather than rem. The content will need to scale appropriately, but the entire width won't be able to go beyond 100vw anyway

2023-07-18 13:23 UTC, SociableSteve commented on assets/style/fonts.css
> +  font-size: 1.5625rem; /* 25px */
Probably 1.6 is a nicer number here

2023-07-18 13:23 UTC, SociableSteve commented on assets/style/fonts.css
> +  font-size: 1.4375rem; /* 23px */
1.4 or 1.5 rem seems good for here?

2023-07-18 13:23 UTC, SociableSteve commented on assets/style/fonts.css
> +  font-size: 1.1875rem; /* 19px */
1.2 seems good here

2023-07-18 14:07 UTC, SociableSteve commented on .stylelintignore
We eventually want to get rid of this? Let's open a ticket to remove it towards the end of the project.

2023-07-18 14:09 UTC, SociableSteve approved these changes, later dismissed

2023-07-18 14:09 UTC, Mariam-mohamed110 commented on .stylelintignore
Ive put it in ignore because its quite confusing seeing the bioconductor errors in the terminal, but will do!

2023-07-18 14:25 UTC, SociableSteve approved these changes

2023-07-18 14:29 UTC, merged