Header implementation - desktop
nearform/bioconductor.org pull request #47
Opened 2023-07-19 09:45 UTC by Mariam-mohamed110

closes #19 

- A new redesigned header taken from figma designs
- Its present in other pages
- Header remains fixed to the top 
- Elements are appropriately tagged

2023-07-19 17:03 UTC, bp289 commented on assets/js/search.js
> +		jQuery("#search-bar").val(q);
good change, much easier to understand now 👍

2023-07-19 20:53 UTC, SociableSteve requested changes
Good work getting this looking and acting as it should. There are a few changes requested to help tidy things up and ensure we're being more dynamic. Let me know if you need help with this.

2023-07-19 20:53 UTC, SociableSteve commented on assets/images/logo_bioconductor.gif
This file is linked from `content/about/logo.md`: https://github.com/nearform/bioconductor.org/blob/feat/header/content/about/logo.md

2023-07-19 20:53 UTC, SociableSteve commented on assets/js/bioconductor.js
It looks like this was adding the right styling to the currently active section of the website. How are we going to do this going forward? See the `developers` design in Figma for an example

2023-07-19 20:53 UTC, SociableSteve commented on assets/style/announcement.css
> +  padding-top: 0.7rem;
Do we need the padding? You're already using flex to centre it

2023-07-19 20:53 UTC, SociableSteve commented on assets/style/bioconductor.css
> +code {
Is this new, and is it needed here? Does it apply to the header? I suspect it's github being strange with formatting but wanted to make sure.

2023-07-19 20:53 UTC, SociableSteve commented on assets/style/bioconductor-v2.css
>  #site-container {
I feel like this should be a class, and we move it to within the different sections. That way we have a full-width section with the content within constrained which will help with later tasks, such as full-width backgrounds.

2023-07-19 20:53 UTC, SociableSteve commented on assets/style/header.css
> +  position: fixed;
Can you double-check with @nickzafiropulos  if he wants this to be fixed to the top of the screen? It's technically possible, but just need to ensure that's his intent. Probably consider `position: sticky` instead.

2023-07-19 20:53 UTC, SociableSteve commented on assets/style/header.css
> +  margin: 0 auto;
You don't need this if the width is 100%. The margin auto would centre it in the space available, but at 100% width there's no centring to be done

2023-07-19 20:53 UTC, SociableSteve commented on assets/style/header.css
> +  height: 140px;   /* announcements height = 140px || no announcements height = 98px */
Can we make the height based on the content instead, then we don't need to worry about the announcements being on or off and it's more dynamic?

2023-07-19 20:53 UTC, SociableSteve commented on assets/style/header.css
> +@media (width >= 700px) {
We should confirm this width is right for the responsiveness. At the moment I think it makes the logo start getting smaller before getting to this width.

2023-07-19 20:53 UTC, SociableSteve commented on assets/style/header.css
> +@media (width <= 700px) {
We probably don't need a block for >700 and one for <=700. If you have one as the default, then the second should start over-riding things as required. This way the breakpoint is only defined in one place.

2023-07-19 20:53 UTC, SociableSteve commented on assets/style/header.css
> +  a {
This will set styling for all links on the page. This is probably not what you intended

2023-07-19 20:53 UTC, SociableSteve commented on assets/style/header.css
> +    transition: background 0.5s ease;
The SVG stroke happens immediately, while the background takes time to transition. Is there a way to make the SVG transition also to give a smoother user experience?

2023-07-19 20:53 UTC, SociableSteve commented on layouts/_announcement.html
> +    <svg xmlns="http://www.w3.org/2000/svg" width="19" height="18" viewBox="0 0 19 18" fill="none">
We should change these to image tags instead for two reasons:

1. It's easier for editors to understand how to change this
2. You can add an alt tag for screen readers

The alternative is to use CSS to switch out these, which reduces the potential for error even further.

2023-07-19 20:53 UTC, SociableSteve commented on layouts/_header.html
> +<!DOCTYPE html>
Don't need the DOCTYPE here. DOCTYPE goes at the very very top of the HTML document

2023-07-19 20:53 UTC, SociableSteve commented on layouts/_header.html
> +  <%= render("/_announcement/") %>
Why is this not in `/components/_announcement`?

2023-07-19 20:53 UTC, SociableSteve commented on layouts/_header.html
Should this be in the components sub-directory?

2023-07-20 08:35 UTC, MariamM110 commented on assets/style/bioconductor.css
> +code {
Github was definitely being strange with formatting, I didn't really add anything in this css file other than removing some css

2023-07-20 09:08 UTC, Mariam-mohamed110 commented on assets/js/bioconductor.js
I thought this code would highlight the element that matches the url of the site?

2023-07-20 09:09 UTC, Mariam-mohamed110 commented on assets/js/bioconductor.js
After looking at the figma design, I realised the nav need to be remained underlined once clicked so we can reuse this but change it around a little bit

2023-07-20 09:19 UTC, Mariam-mohamed110 commented on assets/style/announcement.css
> +  padding-top: 0.7rem;
Turns out there was a conflict in `bioconductor.css` which prevented the flex-box from centring

2023-07-20 09:39 UTC, Mariam-mohamed110 commented on assets/style/header.css
> +  position: fixed;
I double checked with nick and he said to keep it fixed at the top

2023-07-20 10:15 UTC, Mariam-mohamed110 commented on layouts/_header.html
> +  <%= render("/_announcement/") %>
I didnt follow my own ticket 🤦🏼‍♀️

2023-07-21 06:48 UTC, SociableSteve requested changes

2023-07-21 06:48 UTC, SociableSteve commented on assets/js/bioconductor.js
> +      link.classList.remove('active');
Do you need to remove active?

2023-07-21 06:48 UTC, SociableSteve commented on assets/js/bioconductor.js
> +    if (currentPath.match(nav_elements[index])) {
Rather than match, we can now use startsWith. It's slightly more efficient. Alternatively consider `nav_elements[index].test(currentPath)` if all you need to know is if the regex matches or not. `matches` will return the matches for the regex as a array.

2023-07-21 06:48 UTC, SociableSteve commented on assets/js/bioconductor.js
This is a good update with just a bit of tidying up to do.

2023-07-21 06:48 UTC, SociableSteve commented on assets/js/search.js
>  var initSearch = function() {
This is a good opportunity to remove the jQuery, however we can do that later if you prefer.

2023-07-21 06:48 UTC, SociableSteve commented on assets/style/announcement.css
> +  height: 3rem;
Rather than setting the height explicitly it might be better to set a padding and let the height be dynamic, that way we're not constraining multi-line text, or forcing this to be wrong. padding-top and padding-bottom of 0.8rem might be good

2023-07-21 06:48 UTC, SociableSteve commented on assets/style/announcement.css
> +  width: 100%;
Do you need to set this to 100%? div is a block element so 100% width by default.

2023-07-21 06:48 UTC, SociableSteve commented on assets/style/announcement.css
> +    background-color: #070707;
do we have a variable for this colour?

2023-07-21 06:48 UTC, SociableSteve commented on assets/style/announcement.css
> +.announcement-default {
If you put this on `.announcement`, then you don't need announcement-default. The later styles can be used to change things if they don't match and it's one less thing for future maintainers to remember.

2023-07-21 06:48 UTC, SociableSteve commented on assets/style/bioconductor-v2.css
> +  width: 100%;
body is a block element, so 100% width by default.

2023-07-21 06:48 UTC, SociableSteve commented on assets/style/header.css
> +.site-masthead {
You can probably drop the `.site-masthead` and use `header` instead.

2023-07-21 06:48 UTC, SociableSteve commented on assets/style/header.css
> +  width: 100%;
header is a block element so 100% width by default

2023-07-21 06:48 UTC, SociableSteve commented on assets/style/header.css
> +.header-size {
we'll be adding a .container in another PR to set the sizes. Additionally can we set the size based on the content rather than specifying a pixel height? It's more flexible that way, in case there is a lot more content added or the logo size is increased, for example.

2023-07-21 06:48 UTC, SociableSteve commented on assets/style/header.css
> +  color: #070707;
Is there a variable for this colour?

2023-07-21 06:48 UTC, SociableSteve commented on assets/style/header.css
> +  gap: 32px;
2rem please

2023-07-21 06:48 UTC, SociableSteve commented on assets/style/header.css
> +  width: 240px;
This should probably be in rem. Try changing your browsers default font size to large and see if it still seems right.

2023-07-21 06:48 UTC, SociableSteve commented on assets/style/header.css
> +  width: 201px;
Do you need to set a height and width here? A better option might be to do it on the image tag to reduce CLS. The browser will probably have the image tag in the HTML before it's got the styling, so having the dimensions in the img tag means the browser will set the size straight away, rather than it changing size after the css loads.

2023-07-21 06:48 UTC, SociableSteve commented on layouts/components/_announcement.html
We can probably drop the underscores from the file names. These were largerly used to denote they were components, but since they're in a components directory they aren't needed.

2023-07-21 06:48 UTC, SociableSteve commented on layouts/components/_header.html
> +          alt="Bioconductor - open source software for bioinformatics"
In general the alt tag should describe the image rather than the location. However as a linked image it should describe what the link goes, so in this case `Bioconductor home`. https://help.siteimprove.com/support/solutions/articles/80000863904-accessibility-image-alt-text-best-practices is a good resource

2023-07-21 06:48 UTC, SociableSteve commented on layouts/components/_header.html
> +          <img
An alternative approach would be to place this as a background image on the search box, since it doesn't add anything in terms of content here. Having it in the flow means screen readers will probably try to understand it. The alternative would probably be to understand how to hide this from screen readers.

2023-07-21 06:48 UTC, SociableSteve commented on layouts/components/_header.html
> +          >Get Started
Is the spans only use here for making this bold? Could this be done on the a tag above? `a[href='/install'] { }`

2023-07-21 06:48 UTC, SociableSteve commented on layouts/course.html
> +    <%= render("/components/_header/") %>
The nav should be able since it supplies skip links for screen readers. We may not even need the `_nav` element in the future since we're using semantic landmarks

2023-07-21 08:45 UTC, Mariam-mohamed110 commented on assets/js/search.js
>  var initSearch = function() {
I think its best to do that later for another ticket thats specific to removing the jquery, I only altered the search as I realised it wasnt working due to different class and id naming

2023-07-21 09:36 UTC, Mariam-mohamed110 commented on layouts/components/_header.html
> +          >Get Started
The span actually does have important css ill add a name to this span instead of using `.header-button span {}` to show its importance

2023-07-21 12:16 UTC, SociableSteve approved these changes
Approved for merging. Will pull any tidy up work into another ticket.

2023-07-21 12:19 UTC, merged