Footer - desktop
nearform/bioconductor.org pull request #51
Opened 2023-07-19 13:22 UTC by bp289

closes #50 
Changes made:
- New svg files added for images( logos and social media)
- New footer layout was added called "_footer_new", acceptance criteria say to only change the home page, however, it turns out that changing anything about the footer changes the rest of the layouts, so all pages will have this footer.
- New CSS file added for the footer, with relevant styling as per design doc.

2023-07-19 14:38 UTC, Mariam-mohamed110 commented on assets/style/footer.css
> +  margin-top: 0.9375rem; /* 15px  */
We will probably need to speak to Nick about this but we should keep the rems to 1/2 decimal place ◡̈

2023-07-19 14:49 UTC, bp289 commented on assets/style/footer.css
> +  margin-top: 0.9375rem; /* 15px  */
i guess that can just be changed to 16 to make 1 tbh, since its so close

2023-07-19 15:09 UTC, Mariam-mohamed110 commented on layouts/default.html
Theres this file and the course.html, both I think would require the new footer just in case there are deep pages that we havent checked yet

2023-07-19 17:06 UTC, bp289 commented on layouts/default.html
true, however I didnt want to change it just since the ticket said to only change it on the home page, but since it seem like we cant specifically change the home page, this is probably the correct thing to do, thanks 👍

2023-07-21 07:18 UTC, SociableSteve requested changes

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +  clear: both;
Don't need clear: both. The new layout will fix the need for this, so can remove it from here.

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +  margin-bottom: 0;
There's nothing underneath, so no need for a margin-bottom.

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +  height: 29.25rem; /* 468px */
Let's make the height dynamic based on the content. It's more dynamic then in case the content ever changes.

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +  font-size: 70%;
0.7rem rather than %

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +  color: var(--default-white, #fff);
I think we don't need a var for white?

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +.global-footer {
One thing to consider is that the default way that things size is based on the content, rather than the border. So 100% would be 100% + padding. It's a bit annoying and misleading at times. To fix that you can use `box-sizing: border-box` which will tell the browser the sizes are based on border position rather than content position.

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +  max-width: 87.5rem; /* 1400px */
the 1400px is a fixed size, so should be in px rather than rem. rem is good for things which need to scale with users preference, but the width of the site doesn't

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +  padding: 0px;
Padding is 0 already

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +.link-container-inner {
Can we move this below `.link-container`? It's not a big thing but conceptually it's lower down in the DOM hierarchy so having it below makes it easier to scan what's happening.

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +  display: flex;
Since this is used for layout, would grid be a better option? That way you don't need to set the width on `link-container-inner` and can control the layout from here.

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +.list-container {
A small thing but putting a space between blocks helps, especially when elements are named similarly

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +.text-footer {
Can this be set on `footer` instead?

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +.global-footer {
You can target `footer` instead of needing this class.

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +.copyright p {
Rather than this - change it to one p and then use a `<br />` to insert a line break.

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +  margin-top: 1rem; /* 15px  */
I feel like this is for alignment. Since the parent is a flex, we should use to centre things vertically instead. That way if something changes, like the size of the logo, things will update more dynamically.

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +h3 {
This will change the colour of h3 globally. That's probably not what you wanted. You probably want something like [:is](https://developer.mozilla.org/en-US/docs/Web/CSS/:is)

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +@media (width <= 768px) {
The standard would be to use `max-width: 768px` rather than `width <= 768px`. It achieves the same thing, just max-width is more widely used.

2023-07-21 07:18 UTC, SociableSteve commented on assets/style/footer.css
> +    height: auto;
This will probably not be needed if you change the footer height to be based on content from the start.

2023-07-21 07:18 UTC, SociableSteve commented on layouts/_footer_new.html
move to `/components/footer.html`

2023-07-21 07:18 UTC, SociableSteve commented on layouts/_footer_new.html
> +      <div class="link-container-inner">
We should consider renaming one of these things to nav, since it's a set of navigation links.

2023-07-21 07:18 UTC, SociableSteve commented on layouts/_footer_new.html
> +          >
Can we make these formatted a bit nicer. Moving the ending bracket for a tag to another line, while semantically correct, is hard to read and understand what's happening.

2023-07-21 07:18 UTC, SociableSteve commented on layouts/_footer_new.html
> +          <span>
Do we need a span here?

2023-07-21 07:18 UTC, SociableSteve commented on layouts/default.html
> +        <% else %>
I'm glad we're replacing this, and somewhat surprised this still worked. Your formatter probably needs turning off and this putting back as it was, please.

2023-07-21 07:27 UTC, SociableSteve commented on assets/style/footer.css
> +@media (width <= 768px) {
Ignore this, seems the more modern way is what you've done.

2023-07-21 12:17 UTC, SociableSteve submitted a review, later dismissed
Approved for merging. Will pull any tidy up work into another ticket.

2023-07-21 12:25 UTC, merged