Header - mobile
nearform/bioconductor.org pull request #70
Opened 2023-07-24 13:49 UTC by Mariam-mohamed110

closes #40 

- When the viewport width is less than 768px, the layout changes to mobile for header

2023-07-25 16:14 UTC, SociableSteve commented
Linter says no! 😢

2023-07-26 07:16 UTC, SociableSteve commented
You have multiple elements with the same ID. ID's need to be unique. These should probably be classes instead.

2023-07-26 10:56 UTC, SociableSteve requested changes

2023-07-26 10:56 UTC, SociableSteve commented on layouts/components/header.html
> +        <a class="format-bold mobile-link" href="/developers/"
The formatting 😬 Can you keep the tag close on the same line as the tag open where properties are not split over multiple lines please?

2023-07-26 11:09 UTC, SociableSteve commented
Looks nice but the content is still visible underneath and can be scrolled while in the menu.

![image](https://github.com/nearform/bioconductor.org/assets/52213009/5ce00893-d747-446f-82cc-9a67d635f75a)

2023-07-26 12:00 UTC, SociableSteve commented
![image](https://github.com/nearform/bioconductor.org/assets/52213009/77be87ee-ab41-4523-b5f3-48de74f8e6d3)

Some kind of line is now crossing the logo 😬 this might gonna get annoying

2023-07-27 09:18 UTC, bp289 approved these changes

2023-07-27 09:31 UTC, merged