Homepage - Hero
nearform/bioconductor.org pull request #73
Opened 2023-07-25 10:18 UTC by bp289

closes #72 
Changes made:
Fonts.css classes changed to suitable names. 
New CSS file for buttons.

2023-07-25 10:36 UTC, Mariam-mohamed110 commented on assets/style/buttons.css
> +.hero-button {
Most of the css here matches the h6 in fonts.css, would it be easier to add another class for hero-button in font css ?

2023-07-26 10:53 UTC, SociableSteve requested changes

2023-07-26 10:53 UTC, SociableSteve commented on assets/style/buttons.css
> +  font-family: inherit;
Do you need inherit?

2023-07-26 10:53 UTC, SociableSteve commented on assets/style/buttons.css
> +/* stylelint-disable */
Why are you disabling linting?

2023-07-26 10:53 UTC, SociableSteve commented on assets/style/buttons.css
> +  margin: auto;
prefer `margin: auto auto 0.3rem;` to keep it all on one line

2023-07-26 10:53 UTC, SociableSteve commented on assets/style/buttons.css
> +  transition: 0.3s;
We should consider `prefers-reduced-motion` for some CSS things, like animations. //cc @Mariam-mohamed110

2023-07-26 10:53 UTC, SociableSteve commented on assets/style/fonts.css
> +.text-h1,
The `.text-h*` classes don't appear to exist. They really shouldn't either - we should by using the relevant h tags.

2023-07-26 10:53 UTC, SociableSteve commented on assets/style/fonts.css
> +  color: #070707;
If this is meant to apply to the entire body content as a default, put it into the `body` block

2023-07-26 10:53 UTC, SociableSteve commented on assets/style/hero.css
> +.hero {
We have a `.container` class for constraining the width. Prefer that so it's in one place to change if we ever decide to.

2023-07-26 10:53 UTC, SociableSteve commented on assets/style/hero.css
> +  margin: 72px auto;
do we always want 72px, or should it be 4.5rem?

2023-07-26 10:53 UTC, SociableSteve commented on assets/style/hero.css
> +    font-size: 1rem;
Did it ever change from 1rem?

2023-07-26 12:41 UTC, bp289 commented on assets/style/fonts.css
> +.text-h1,
I was using this or the button on the hero as it matched the styling for the h6, I was going to originally use a h6 but  Isnt it an accesibility issue if I use a `h6` before a `h3` in the dom?

2023-07-26 12:48 UTC, bp289 commented on assets/style/hero.css
> +    font-size: 1rem;
The hero should have the `text-large` class applied so it should be 1.25 rem to start off with.

2023-07-26 13:03 UTC, bp289 commented on assets/style/buttons.css
> +/* stylelint-disable */
sorry forgot to change this back, updated now!

2023-07-27 09:35 UTC, Mariam-mohamed110 approved these changes

2023-07-27 09:38 UTC, merged