Homepage - Learn section
nearform/bioconductor.org pull request #80
Opened 2023-07-26 09:26 UTC by Mariam-mohamed110

closes #74 

- Learn section looks similar to figma designs 

Important notes:
- svgs cannot change colours when transition is applied if its in an img, so it must remain as an inline svg
- If the background colour is set to a gradient, a transition cannot be applied too because CSS doesnt support it yet (Will research more on this later)

2023-07-26 11:05 UTC, SociableSteve requested changes

2023-07-26 11:05 UTC, SociableSteve commented on assets/style/bioconductor-v2.css
> +  background: var(--neutral-n50);
Is this the right background colour for all pages?

2023-07-26 11:05 UTC, SociableSteve commented on assets/style/fonts.css
> +.text-hero {
Where is this added in the code? I can't find it 😬

2023-07-26 11:05 UTC, SociableSteve commented on content/index.html
> +        <section>
Would these all be considered separate sections or is the entire row across a section?

2023-07-26 11:05 UTC, SociableSteve commented on content/index.html
> +                    <time datetime="2023-06-30">30 June</time> -
Nice use of the `time` tag 👍

2023-07-26 11:10 UTC, Mariam-mohamed110 commented on assets/style/bioconductor-v2.css
> +  background: var(--neutral-n50);
Most of the pages do have this colour as the background other than packages and about pages. We were unsure how to go about this because theres a set width which doesnt allow the background colour to overflow the container

2023-07-26 11:11 UTC, Mariam-mohamed110 commented on assets/style/fonts.css
> +.text-hero {
This particular branch had been branched off from the homepage branch that biraj created which has some homepage changes, I think this was for his hero changes but thats not necessary for this branch

2023-07-26 11:12 UTC, Mariam-mohamed110 commented on content/index.html
> +                    <time datetime="2023-06-30">30 June</time> -
@bp289 done this 👏🏼

2023-07-26 11:20 UTC, Mariam-mohamed110 commented on content/index.html
> +        <section>
Im not sure about this because I only pulled birajs code for homepage, i think hes redoing that section currently but im unsure

2023-07-26 12:02 UTC, SociableSteve commented on assets/style/bioconductor-v2.css
> +  background: var(--neutral-n50);
this is why we have the container, which will allow you to set a section the entire width across, then add a container

If this is the default background colour, it's probably better on the body tag rather than the main tag.

2023-07-26 14:04 UTC, bp289 commented on content/index.html
> +        <section>
This should be changed on #81

2023-07-27 09:20 UTC, bp289 commented on assets/style/buttons.css
> +}
can probably remove this as it is on the hero branch

2023-07-27 10:33 UTC, bp289 approved these changes

2023-07-27 10:40 UTC, merged